name: ordbokapi-redis-local-dev
services:
  redis:
    image: redis/redis-stack:7.2.0-v14
    environment:
      REDIS_ARGS: "--loglevel debug --maxmemory-policy noeviction"
      REDISEARCH_ARGS: "MAXAGGREGATERESULTS 500000 MAXPREFIXEXPANSIONS 500000 MAXSEARCHRESULTS 500000 MINPREFIX 1 DEFAULT_DIALECT 3"
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    volumes:
      - ./.redis:/data
