name: Main Branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        shell: bash
        run: |
          cargo clippy --release --all-targets --all-features -- \
            -D clippy::suspicious -D clippy::style -D clippy::complexity \
            -D clippy::perf -D clippy::dbg_macro -D clippy::todo \
            -D clippy::unimplemented -D warnings

      # - name: Test
      #   if: always() && (matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu') || (matrix.os == 'windows-latest' && matrix.target == 'x86_64-pc-windows-msvc') || (matrix.os == 'macos-latest' && matrix.target == 'x86_64-apple-darwin')
      #   run: cargo test --release --target ${{ matrix.target }}
