# SPDX-FileCopyrightText: Copyright (C) 2026 Adaline Simonian
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Ordbok API.
#
# Ordbok API is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Ordbok API is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ordbok API. If not, see <https://www.gnu.org/licenses/>.

name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  merge_group:

concurrency:
  group: ${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          components: rustfmt, clippy
          rustflags: ""

      - name: Build
        run: cargo build --all-features --release --target ${{ matrix.target }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        shell: bash
        run: |
          cargo clippy --release --all-targets --all-features -- \
            -D clippy::suspicious -D clippy::style -D clippy::complexity \
            -D clippy::perf -D clippy::dbg_macro -D clippy::todo \
            -D clippy::unimplemented -D warnings

      - name: Run tests
        run: cargo test --release --all-features --target ${{ matrix.target }}
