name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  merge_group:

concurrency:
  group: ${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          rustflags: ""

      - name: Build
        run: cargo build --all-features --release --target ${{ matrix.target }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        shell: bash
        run: |
          cargo clippy --release --all-targets --all-features -- \
            -D clippy::suspicious -D clippy::style -D clippy::complexity \
            -D clippy::perf -D clippy::dbg_macro -D clippy::todo \
            -D clippy::unimplemented -D warnings

      - name: Run tests
        run: cargo test --release --all-features --target ${{ matrix.target }}
