# SPDX-FileCopyrightText: Copyright (C) 2026 Adaline Simonian
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of Ordbok API.
#
# Ordbok API is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Ordbok API is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Ordbok API. If not, see <https://www.gnu.org/licenses/>.

name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docker-compose.yml"
      - "*.ps1"
      - "*.sh"
  merge_group:

concurrency:
  group: ${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          target: ${{ matrix.target }}
          components: rustfmt, clippy
          rustflags: ""

      - name: Setup UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Build
        run: cargo build --all-features --release --target ${{ matrix.target }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check clippy
        shell: bash
        run: |
          cargo clippy --release --all-targets --all-features -- \
            -D clippy::all -D clippy::pedantic -D clippy::nursery \
            -A clippy::missing_errors_doc -A clippy::missing_panics_doc \
            -A clippy::doc_markdown -A clippy::module_name_repetitions \
            -D warnings

      - name: Run tests
        run: cargo test --release --all-features --target ${{ matrix.target }}

      - name: Lint licences
        run: uvx reuse lint
